// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: voucher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type VoucherInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId      int64  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle    string `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Rules       string `protobuf:"bytes,5,opt,name=rules,proto3" json:"rules,omitempty"`
	PayValue    int64  `protobuf:"varint,6,opt,name=pay_value,json=payValue,proto3" json:"pay_value,omitempty"`
	ActualValue int64  `protobuf:"varint,7,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	Type        int32  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	Status      int32  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime  string `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *VoucherInfo) Reset() {
	*x = VoucherInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherInfo) ProtoMessage() {}

func (x *VoucherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherInfo.ProtoReflect.Descriptor instead.
func (*VoucherInfo) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{0}
}

func (x *VoucherInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VoucherInfo) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *VoucherInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VoucherInfo) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *VoucherInfo) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *VoucherInfo) GetPayValue() int64 {
	if x != nil {
		return x.PayValue
	}
	return 0
}

func (x *VoucherInfo) GetActualValue() int64 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *VoucherInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VoucherInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VoucherInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *VoucherInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type SeckillVoucherInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId  int64  `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	Stock      int32  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	BeginTime  string `protobuf:"bytes,3,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime    string `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreateTime string `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime string `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *SeckillVoucherInfo) Reset() {
	*x = SeckillVoucherInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillVoucherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillVoucherInfo) ProtoMessage() {}

func (x *SeckillVoucherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillVoucherInfo.ProtoReflect.Descriptor instead.
func (*SeckillVoucherInfo) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillVoucherInfo) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

func (x *SeckillVoucherInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SeckillVoucherInfo) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *SeckillVoucherInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SeckillVoucherInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SeckillVoucherInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type AddVoucherReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId      int64  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle    string `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Rules       string `protobuf:"bytes,4,opt,name=rules,proto3" json:"rules,omitempty"`
	PayValue    int64  `protobuf:"varint,5,opt,name=pay_value,json=payValue,proto3" json:"pay_value,omitempty"`
	ActualValue int64  `protobuf:"varint,6,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	Type        int32  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AddVoucherReq) Reset() {
	*x = AddVoucherReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVoucherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVoucherReq) ProtoMessage() {}

func (x *AddVoucherReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVoucherReq.ProtoReflect.Descriptor instead.
func (*AddVoucherReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{2}
}

func (x *AddVoucherReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *AddVoucherReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddVoucherReq) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *AddVoucherReq) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *AddVoucherReq) GetPayValue() int64 {
	if x != nil {
		return x.PayValue
	}
	return 0
}

func (x *AddVoucherReq) GetActualValue() int64 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *AddVoucherReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type AddVoucherResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId int64 `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
}

func (x *AddVoucherResp) Reset() {
	*x = AddVoucherResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVoucherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVoucherResp) ProtoMessage() {}

func (x *AddVoucherResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVoucherResp.ProtoReflect.Descriptor instead.
func (*AddVoucherResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{3}
}

func (x *AddVoucherResp) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

type AddSeckillVoucherReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId int64  `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	Stock     int32  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	BeginTime string `protobuf:"bytes,3,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime   string `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *AddSeckillVoucherReq) Reset() {
	*x = AddSeckillVoucherReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeckillVoucherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeckillVoucherReq) ProtoMessage() {}

func (x *AddSeckillVoucherReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeckillVoucherReq.ProtoReflect.Descriptor instead.
func (*AddSeckillVoucherReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{4}
}

func (x *AddSeckillVoucherReq) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

func (x *AddSeckillVoucherReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddSeckillVoucherReq) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *AddSeckillVoucherReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type AddSeckillVoucherResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddSeckillVoucherResp) Reset() {
	*x = AddSeckillVoucherResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeckillVoucherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeckillVoucherResp) ProtoMessage() {}

func (x *AddSeckillVoucherResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeckillVoucherResp.ProtoReflect.Descriptor instead.
func (*AddSeckillVoucherResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{5}
}

func (x *AddSeckillVoucherResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetVoucherReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId int64 `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
}

func (x *GetVoucherReq) Reset() {
	*x = GetVoucherReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoucherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoucherReq) ProtoMessage() {}

func (x *GetVoucherReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoucherReq.ProtoReflect.Descriptor instead.
func (*GetVoucherReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{6}
}

func (x *GetVoucherReq) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

type GetVoucherResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voucher        *VoucherInfo        `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
	SeckillVoucher *SeckillVoucherInfo `protobuf:"bytes,2,opt,name=seckill_voucher,json=seckillVoucher,proto3" json:"seckill_voucher,omitempty"`
}

func (x *GetVoucherResp) Reset() {
	*x = GetVoucherResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoucherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoucherResp) ProtoMessage() {}

func (x *GetVoucherResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoucherResp.ProtoReflect.Descriptor instead.
func (*GetVoucherResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{7}
}

func (x *GetVoucherResp) GetVoucher() *VoucherInfo {
	if x != nil {
		return x.Voucher
	}
	return nil
}

func (x *GetVoucherResp) GetSeckillVoucher() *SeckillVoucherInfo {
	if x != nil {
		return x.SeckillVoucher
	}
	return nil
}

type ListVouchersByShopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int64 `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *ListVouchersByShopReq) Reset() {
	*x = ListVouchersByShopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVouchersByShopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVouchersByShopReq) ProtoMessage() {}

func (x *ListVouchersByShopReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVouchersByShopReq.ProtoReflect.Descriptor instead.
func (*ListVouchersByShopReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{8}
}

func (x *ListVouchersByShopReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ListVouchersByShopResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vouchers []*VoucherInfo `protobuf:"bytes,1,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
}

func (x *ListVouchersByShopResp) Reset() {
	*x = ListVouchersByShopResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVouchersByShopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVouchersByShopResp) ProtoMessage() {}

func (x *ListVouchersByShopResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVouchersByShopResp.ProtoReflect.Descriptor instead.
func (*ListVouchersByShopResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{9}
}

func (x *ListVouchersByShopResp) GetVouchers() []*VoucherInfo {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

type CheckVoucherStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId int64 `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
}

func (x *CheckVoucherStockReq) Reset() {
	*x = CheckVoucherStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckVoucherStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVoucherStockReq) ProtoMessage() {}

func (x *CheckVoucherStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVoucherStockReq.ProtoReflect.Descriptor instead.
func (*CheckVoucherStockReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{10}
}

func (x *CheckVoucherStockReq) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

type CheckVoucherStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasStock bool  `protobuf:"varint,1,opt,name=has_stock,json=hasStock,proto3" json:"has_stock,omitempty"`
	Stock    int32 `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *CheckVoucherStockResp) Reset() {
	*x = CheckVoucherStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckVoucherStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVoucherStockResp) ProtoMessage() {}

func (x *CheckVoucherStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVoucherStockResp.ProtoReflect.Descriptor instead.
func (*CheckVoucherStockResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{11}
}

func (x *CheckVoucherStockResp) GetHasStock() bool {
	if x != nil {
		return x.HasStock
	}
	return false
}

func (x *CheckVoucherStockResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type DeductVoucherStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoucherId int64 `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
}

func (x *DeductVoucherStockReq) Reset() {
	*x = DeductVoucherStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductVoucherStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductVoucherStockReq) ProtoMessage() {}

func (x *DeductVoucherStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductVoucherStockReq.ProtoReflect.Descriptor instead.
func (*DeductVoucherStockReq) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{12}
}

func (x *DeductVoucherStockReq) GetVoucherId() int64 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

type DeductVoucherStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeductVoucherStockResp) Reset() {
	*x = DeductVoucherStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductVoucherStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductVoucherStockResp) ProtoMessage() {}

func (x *DeductVoucherStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductVoucherStockResp.ProtoReflect.Descriptor instead.
func (*DeductVoucherStockResp) Descriptor() ([]byte, []int) {
	return file_voucher_proto_rawDescGZIP(), []int{13}
}

func (x *DeductVoucherStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_voucher_proto protoreflect.FileDescriptor

var file_voucher_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0xad, 0x02, 0x0a, 0x0b, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x63,
	0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xc5, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x31, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6b, 0x69,
	0x6c, 0x6c, 0x5f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69,
	0x6c, 0x6c, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x73,
	0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0x30, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53,
	0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22,
	0x4a, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x42,
	0x79, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x08, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x22, 0x35, 0x0a, 0x14, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x68,
	0x61, 0x73, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x68, 0x61, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x36,
	0x0a, 0x15, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xdd, 0x03, 0x0a, 0x07, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x41,
	0x64, 0x64, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x76,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x52, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x65, 0x63, 0x6b,
	0x69, 0x6c, 0x6c, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x76, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x55, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x1e,
	0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x1f,
	0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x52, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x55, 0x0a, 0x12, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x76, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x76, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_voucher_proto_rawDescOnce sync.Once
	file_voucher_proto_rawDescData = file_voucher_proto_rawDesc
)

func file_voucher_proto_rawDescGZIP() []byte {
	file_voucher_proto_rawDescOnce.Do(func() {
		file_voucher_proto_rawDescData = protoimpl.X.CompressGZIP(file_voucher_proto_rawDescData)
	})
	return file_voucher_proto_rawDescData
}

var file_voucher_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_voucher_proto_goTypes = []interface{}{
	(*VoucherInfo)(nil),            // 0: voucher.VoucherInfo
	(*SeckillVoucherInfo)(nil),     // 1: voucher.SeckillVoucherInfo
	(*AddVoucherReq)(nil),          // 2: voucher.AddVoucherReq
	(*AddVoucherResp)(nil),         // 3: voucher.AddVoucherResp
	(*AddSeckillVoucherReq)(nil),   // 4: voucher.AddSeckillVoucherReq
	(*AddSeckillVoucherResp)(nil),  // 5: voucher.AddSeckillVoucherResp
	(*GetVoucherReq)(nil),          // 6: voucher.GetVoucherReq
	(*GetVoucherResp)(nil),         // 7: voucher.GetVoucherResp
	(*ListVouchersByShopReq)(nil),  // 8: voucher.ListVouchersByShopReq
	(*ListVouchersByShopResp)(nil), // 9: voucher.ListVouchersByShopResp
	(*CheckVoucherStockReq)(nil),   // 10: voucher.CheckVoucherStockReq
	(*CheckVoucherStockResp)(nil),  // 11: voucher.CheckVoucherStockResp
	(*DeductVoucherStockReq)(nil),  // 12: voucher.DeductVoucherStockReq
	(*DeductVoucherStockResp)(nil), // 13: voucher.DeductVoucherStockResp
}
var file_voucher_proto_depIdxs = []int32{
	0,  // 0: voucher.GetVoucherResp.voucher:type_name -> voucher.VoucherInfo
	1,  // 1: voucher.GetVoucherResp.seckill_voucher:type_name -> voucher.SeckillVoucherInfo
	0,  // 2: voucher.ListVouchersByShopResp.vouchers:type_name -> voucher.VoucherInfo
	2,  // 3: voucher.Voucher.AddVoucher:input_type -> voucher.AddVoucherReq
	4,  // 4: voucher.Voucher.AddSeckillVoucher:input_type -> voucher.AddSeckillVoucherReq
	6,  // 5: voucher.Voucher.GetVoucher:input_type -> voucher.GetVoucherReq
	8,  // 6: voucher.Voucher.ListVouchersByShop:input_type -> voucher.ListVouchersByShopReq
	10, // 7: voucher.Voucher.CheckVoucherStock:input_type -> voucher.CheckVoucherStockReq
	12, // 8: voucher.Voucher.DeductVoucherStock:input_type -> voucher.DeductVoucherStockReq
	3,  // 9: voucher.Voucher.AddVoucher:output_type -> voucher.AddVoucherResp
	5,  // 10: voucher.Voucher.AddSeckillVoucher:output_type -> voucher.AddSeckillVoucherResp
	7,  // 11: voucher.Voucher.GetVoucher:output_type -> voucher.GetVoucherResp
	9,  // 12: voucher.Voucher.ListVouchersByShop:output_type -> voucher.ListVouchersByShopResp
	11, // 13: voucher.Voucher.CheckVoucherStock:output_type -> voucher.CheckVoucherStockResp
	13, // 14: voucher.Voucher.DeductVoucherStock:output_type -> voucher.DeductVoucherStockResp
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_voucher_proto_init() }
func file_voucher_proto_init() {
	if File_voucher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_voucher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillVoucherInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVoucherReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVoucherResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeckillVoucherReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeckillVoucherResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoucherReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoucherResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVouchersByShopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVouchersByShopResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckVoucherStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckVoucherStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductVoucherStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductVoucherStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_voucher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voucher_proto_goTypes,
		DependencyIndexes: file_voucher_proto_depIdxs,
		MessageInfos:      file_voucher_proto_msgTypes,
	}.Build()
	File_voucher_proto = out.File
	file_voucher_proto_rawDesc = nil
	file_voucher_proto_goTypes = nil
	file_voucher_proto_depIdxs = nil
}
