// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: voucher.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Voucher_AddVoucher_FullMethodName         = "/voucher.Voucher/AddVoucher"
	Voucher_AddSeckillVoucher_FullMethodName  = "/voucher.Voucher/AddSeckillVoucher"
	Voucher_GetVoucher_FullMethodName         = "/voucher.Voucher/GetVoucher"
	Voucher_ListVouchersByShop_FullMethodName = "/voucher.Voucher/ListVouchersByShop"
	Voucher_CheckVoucherStock_FullMethodName  = "/voucher.Voucher/CheckVoucherStock"
	Voucher_DeductVoucherStock_FullMethodName = "/voucher.Voucher/DeductVoucherStock"
)

// VoucherClient is the client API for Voucher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherClient interface {
	// Add voucher
	AddVoucher(ctx context.Context, in *AddVoucherReq, opts ...grpc.CallOption) (*AddVoucherResp, error)
	// Add seckill voucher
	AddSeckillVoucher(ctx context.Context, in *AddSeckillVoucherReq, opts ...grpc.CallOption) (*AddSeckillVoucherResp, error)
	// Get voucher by ID
	GetVoucher(ctx context.Context, in *GetVoucherReq, opts ...grpc.CallOption) (*GetVoucherResp, error)
	// List vouchers by shop
	ListVouchersByShop(ctx context.Context, in *ListVouchersByShopReq, opts ...grpc.CallOption) (*ListVouchersByShopResp, error)
	// Check voucher stock
	CheckVoucherStock(ctx context.Context, in *CheckVoucherStockReq, opts ...grpc.CallOption) (*CheckVoucherStockResp, error)
	// Deduct voucher stock
	DeductVoucherStock(ctx context.Context, in *DeductVoucherStockReq, opts ...grpc.CallOption) (*DeductVoucherStockResp, error)
}

type voucherClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherClient(cc grpc.ClientConnInterface) VoucherClient {
	return &voucherClient{cc}
}

func (c *voucherClient) AddVoucher(ctx context.Context, in *AddVoucherReq, opts ...grpc.CallOption) (*AddVoucherResp, error) {
	out := new(AddVoucherResp)
	err := c.cc.Invoke(ctx, Voucher_AddVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherClient) AddSeckillVoucher(ctx context.Context, in *AddSeckillVoucherReq, opts ...grpc.CallOption) (*AddSeckillVoucherResp, error) {
	out := new(AddSeckillVoucherResp)
	err := c.cc.Invoke(ctx, Voucher_AddSeckillVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherClient) GetVoucher(ctx context.Context, in *GetVoucherReq, opts ...grpc.CallOption) (*GetVoucherResp, error) {
	out := new(GetVoucherResp)
	err := c.cc.Invoke(ctx, Voucher_GetVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherClient) ListVouchersByShop(ctx context.Context, in *ListVouchersByShopReq, opts ...grpc.CallOption) (*ListVouchersByShopResp, error) {
	out := new(ListVouchersByShopResp)
	err := c.cc.Invoke(ctx, Voucher_ListVouchersByShop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherClient) CheckVoucherStock(ctx context.Context, in *CheckVoucherStockReq, opts ...grpc.CallOption) (*CheckVoucherStockResp, error) {
	out := new(CheckVoucherStockResp)
	err := c.cc.Invoke(ctx, Voucher_CheckVoucherStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherClient) DeductVoucherStock(ctx context.Context, in *DeductVoucherStockReq, opts ...grpc.CallOption) (*DeductVoucherStockResp, error) {
	out := new(DeductVoucherStockResp)
	err := c.cc.Invoke(ctx, Voucher_DeductVoucherStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServer is the server API for Voucher service.
// All implementations must embed UnimplementedVoucherServer
// for forward compatibility
type VoucherServer interface {
	// Add voucher
	AddVoucher(context.Context, *AddVoucherReq) (*AddVoucherResp, error)
	// Add seckill voucher
	AddSeckillVoucher(context.Context, *AddSeckillVoucherReq) (*AddSeckillVoucherResp, error)
	// Get voucher by ID
	GetVoucher(context.Context, *GetVoucherReq) (*GetVoucherResp, error)
	// List vouchers by shop
	ListVouchersByShop(context.Context, *ListVouchersByShopReq) (*ListVouchersByShopResp, error)
	// Check voucher stock
	CheckVoucherStock(context.Context, *CheckVoucherStockReq) (*CheckVoucherStockResp, error)
	// Deduct voucher stock
	DeductVoucherStock(context.Context, *DeductVoucherStockReq) (*DeductVoucherStockResp, error)
	mustEmbedUnimplementedVoucherServer()
}

// UnimplementedVoucherServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServer struct {
}

func (UnimplementedVoucherServer) AddVoucher(context.Context, *AddVoucherReq) (*AddVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVoucher not implemented")
}
func (UnimplementedVoucherServer) AddSeckillVoucher(context.Context, *AddSeckillVoucherReq) (*AddSeckillVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSeckillVoucher not implemented")
}
func (UnimplementedVoucherServer) GetVoucher(context.Context, *GetVoucherReq) (*GetVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucher not implemented")
}
func (UnimplementedVoucherServer) ListVouchersByShop(context.Context, *ListVouchersByShopReq) (*ListVouchersByShopResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVouchersByShop not implemented")
}
func (UnimplementedVoucherServer) CheckVoucherStock(context.Context, *CheckVoucherStockReq) (*CheckVoucherStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVoucherStock not implemented")
}
func (UnimplementedVoucherServer) DeductVoucherStock(context.Context, *DeductVoucherStockReq) (*DeductVoucherStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductVoucherStock not implemented")
}
func (UnimplementedVoucherServer) mustEmbedUnimplementedVoucherServer() {}

// UnsafeVoucherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServer will
// result in compilation errors.
type UnsafeVoucherServer interface {
	mustEmbedUnimplementedVoucherServer()
}

func RegisterVoucherServer(s grpc.ServiceRegistrar, srv VoucherServer) {
	s.RegisterService(&Voucher_ServiceDesc, srv)
}

func _Voucher_AddVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).AddVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_AddVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).AddVoucher(ctx, req.(*AddVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voucher_AddSeckillVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSeckillVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).AddSeckillVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_AddSeckillVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).AddSeckillVoucher(ctx, req.(*AddSeckillVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voucher_GetVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).GetVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_GetVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).GetVoucher(ctx, req.(*GetVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voucher_ListVouchersByShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVouchersByShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).ListVouchersByShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_ListVouchersByShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).ListVouchersByShop(ctx, req.(*ListVouchersByShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voucher_CheckVoucherStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVoucherStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).CheckVoucherStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_CheckVoucherStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).CheckVoucherStock(ctx, req.(*CheckVoucherStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voucher_DeductVoucherStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductVoucherStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServer).DeductVoucherStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voucher_DeductVoucherStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServer).DeductVoucherStock(ctx, req.(*DeductVoucherStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Voucher_ServiceDesc is the grpc.ServiceDesc for Voucher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Voucher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voucher.Voucher",
	HandlerType: (*VoucherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVoucher",
			Handler:    _Voucher_AddVoucher_Handler,
		},
		{
			MethodName: "AddSeckillVoucher",
			Handler:    _Voucher_AddSeckillVoucher_Handler,
		},
		{
			MethodName: "GetVoucher",
			Handler:    _Voucher_GetVoucher_Handler,
		},
		{
			MethodName: "ListVouchersByShop",
			Handler:    _Voucher_ListVouchersByShop_Handler,
		},
		{
			MethodName: "CheckVoucherStock",
			Handler:    _Voucher_CheckVoucherStock_Handler,
		},
		{
			MethodName: "DeductVoucherStock",
			Handler:    _Voucher_DeductVoucherStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voucher.proto",
}
