// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: shop.proto

package server

import (
	"context"

	"github.com/me-cs/dianping-gozero/rpc/shop/internal/logic"
	"github.com/me-cs/dianping-gozero/rpc/shop/internal/svc"
	"github.com/me-cs/dianping-gozero/rpc/shop/pb"
)

type ShopServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedShopServer
}

func NewShopServer(svcCtx *svc.ServiceContext) *ShopServer {
	return &ShopServer{
		svcCtx: svcCtx,
	}
}

// Get shop by ID
func (s *ShopServer) GetShop(ctx context.Context, in *pb.GetShopReq) (*pb.GetShopResp, error) {
	l := logic.NewGetShopLogic(ctx, s.svcCtx)
	return l.GetShop(in)
}

// List shops by type
func (s *ShopServer) ListShopsByType(ctx context.Context, in *pb.ListShopsByTypeReq) (*pb.ListShopsByTypeResp, error) {
	l := logic.NewListShopsByTypeLogic(ctx, s.svcCtx)
	return l.ListShopsByType(in)
}

// Search shops
func (s *ShopServer) SearchShops(ctx context.Context, in *pb.SearchShopsReq) (*pb.SearchShopsResp, error) {
	l := logic.NewSearchShopsLogic(ctx, s.svcCtx)
	return l.SearchShops(in)
}

// Get shop type by ID
func (s *ShopServer) GetShopType(ctx context.Context, in *pb.GetShopTypeReq) (*pb.GetShopTypeResp, error) {
	l := logic.NewGetShopTypeLogic(ctx, s.svcCtx)
	return l.GetShopType(in)
}

// List all shop types
func (s *ShopServer) ListShopTypes(ctx context.Context, in *pb.ListShopTypesReq) (*pb.ListShopTypesResp, error) {
	l := logic.NewListShopTypesLogic(ctx, s.svcCtx)
	return l.ListShopTypes(in)
}
