// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Order_CreateVoucherOrder_FullMethodName      = "/order.Order/CreateVoucherOrder"
	Order_GetVoucherOrder_FullMethodName         = "/order.Order/GetVoucherOrder"
	Order_ListVoucherOrdersByUser_FullMethodName = "/order.Order/ListVoucherOrdersByUser"
	Order_CancelVoucherOrder_FullMethodName      = "/order.Order/CancelVoucherOrder"
	Order_PayVoucherOrder_FullMethodName         = "/order.Order/PayVoucherOrder"
	Order_UseVoucherOrder_FullMethodName         = "/order.Order/UseVoucherOrder"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	// Create voucher order (seckill)
	CreateVoucherOrder(ctx context.Context, in *CreateVoucherOrderReq, opts ...grpc.CallOption) (*CreateVoucherOrderResp, error)
	// Get voucher order by ID
	GetVoucherOrder(ctx context.Context, in *GetVoucherOrderReq, opts ...grpc.CallOption) (*GetVoucherOrderResp, error)
	// List voucher orders by user
	ListVoucherOrdersByUser(ctx context.Context, in *ListVoucherOrdersByUserReq, opts ...grpc.CallOption) (*ListVoucherOrdersByUserResp, error)
	// Cancel voucher order
	CancelVoucherOrder(ctx context.Context, in *CancelVoucherOrderReq, opts ...grpc.CallOption) (*CancelVoucherOrderResp, error)
	// Pay voucher order
	PayVoucherOrder(ctx context.Context, in *PayVoucherOrderReq, opts ...grpc.CallOption) (*PayVoucherOrderResp, error)
	// Use voucher order
	UseVoucherOrder(ctx context.Context, in *UseVoucherOrderReq, opts ...grpc.CallOption) (*UseVoucherOrderResp, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateVoucherOrder(ctx context.Context, in *CreateVoucherOrderReq, opts ...grpc.CallOption) (*CreateVoucherOrderResp, error) {
	out := new(CreateVoucherOrderResp)
	err := c.cc.Invoke(ctx, Order_CreateVoucherOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetVoucherOrder(ctx context.Context, in *GetVoucherOrderReq, opts ...grpc.CallOption) (*GetVoucherOrderResp, error) {
	out := new(GetVoucherOrderResp)
	err := c.cc.Invoke(ctx, Order_GetVoucherOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ListVoucherOrdersByUser(ctx context.Context, in *ListVoucherOrdersByUserReq, opts ...grpc.CallOption) (*ListVoucherOrdersByUserResp, error) {
	out := new(ListVoucherOrdersByUserResp)
	err := c.cc.Invoke(ctx, Order_ListVoucherOrdersByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelVoucherOrder(ctx context.Context, in *CancelVoucherOrderReq, opts ...grpc.CallOption) (*CancelVoucherOrderResp, error) {
	out := new(CancelVoucherOrderResp)
	err := c.cc.Invoke(ctx, Order_CancelVoucherOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) PayVoucherOrder(ctx context.Context, in *PayVoucherOrderReq, opts ...grpc.CallOption) (*PayVoucherOrderResp, error) {
	out := new(PayVoucherOrderResp)
	err := c.cc.Invoke(ctx, Order_PayVoucherOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UseVoucherOrder(ctx context.Context, in *UseVoucherOrderReq, opts ...grpc.CallOption) (*UseVoucherOrderResp, error) {
	out := new(UseVoucherOrderResp)
	err := c.cc.Invoke(ctx, Order_UseVoucherOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility
type OrderServer interface {
	// Create voucher order (seckill)
	CreateVoucherOrder(context.Context, *CreateVoucherOrderReq) (*CreateVoucherOrderResp, error)
	// Get voucher order by ID
	GetVoucherOrder(context.Context, *GetVoucherOrderReq) (*GetVoucherOrderResp, error)
	// List voucher orders by user
	ListVoucherOrdersByUser(context.Context, *ListVoucherOrdersByUserReq) (*ListVoucherOrdersByUserResp, error)
	// Cancel voucher order
	CancelVoucherOrder(context.Context, *CancelVoucherOrderReq) (*CancelVoucherOrderResp, error)
	// Pay voucher order
	PayVoucherOrder(context.Context, *PayVoucherOrderReq) (*PayVoucherOrderResp, error)
	// Use voucher order
	UseVoucherOrder(context.Context, *UseVoucherOrderReq) (*UseVoucherOrderResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (UnimplementedOrderServer) CreateVoucherOrder(context.Context, *CreateVoucherOrderReq) (*CreateVoucherOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVoucherOrder not implemented")
}
func (UnimplementedOrderServer) GetVoucherOrder(context.Context, *GetVoucherOrderReq) (*GetVoucherOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucherOrder not implemented")
}
func (UnimplementedOrderServer) ListVoucherOrdersByUser(context.Context, *ListVoucherOrdersByUserReq) (*ListVoucherOrdersByUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVoucherOrdersByUser not implemented")
}
func (UnimplementedOrderServer) CancelVoucherOrder(context.Context, *CancelVoucherOrderReq) (*CancelVoucherOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelVoucherOrder not implemented")
}
func (UnimplementedOrderServer) PayVoucherOrder(context.Context, *PayVoucherOrderReq) (*PayVoucherOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayVoucherOrder not implemented")
}
func (UnimplementedOrderServer) UseVoucherOrder(context.Context, *UseVoucherOrderReq) (*UseVoucherOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseVoucherOrder not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_CreateVoucherOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVoucherOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateVoucherOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateVoucherOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateVoucherOrder(ctx, req.(*CreateVoucherOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetVoucherOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoucherOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetVoucherOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetVoucherOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetVoucherOrder(ctx, req.(*GetVoucherOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ListVoucherOrdersByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoucherOrdersByUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ListVoucherOrdersByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ListVoucherOrdersByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ListVoucherOrdersByUser(ctx, req.(*ListVoucherOrdersByUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelVoucherOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelVoucherOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelVoucherOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CancelVoucherOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelVoucherOrder(ctx, req.(*CancelVoucherOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_PayVoucherOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayVoucherOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).PayVoucherOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_PayVoucherOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).PayVoucherOrder(ctx, req.(*PayVoucherOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UseVoucherOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseVoucherOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UseVoucherOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_UseVoucherOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UseVoucherOrder(ctx, req.(*UseVoucherOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVoucherOrder",
			Handler:    _Order_CreateVoucherOrder_Handler,
		},
		{
			MethodName: "GetVoucherOrder",
			Handler:    _Order_GetVoucherOrder_Handler,
		},
		{
			MethodName: "ListVoucherOrdersByUser",
			Handler:    _Order_ListVoucherOrdersByUser_Handler,
		},
		{
			MethodName: "CancelVoucherOrder",
			Handler:    _Order_CancelVoucherOrder_Handler,
		},
		{
			MethodName: "PayVoucherOrder",
			Handler:    _Order_PayVoucherOrder_Handler,
		},
		{
			MethodName: "UseVoucherOrder",
			Handler:    _Order_UseVoucherOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
