// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/me-cs/dianping-gozero/rpc/user/internal/logic"
	"github.com/me-cs/dianping-gozero/rpc/user/internal/svc"
	"github.com/me-cs/dianping-gozero/rpc/user/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Get user by ID
func (s *UserServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// Get user info by ID
func (s *UserServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// Create or update user
func (s *UserServer) SaveUser(ctx context.Context, in *pb.SaveUserReq) (*pb.SaveUserResp, error) {
	l := logic.NewSaveUserLogic(ctx, s.svcCtx)
	return l.SaveUser(in)
}

// Send verification code
func (s *UserServer) SendCode(ctx context.Context, in *pb.SendCodeReq) (*pb.SendCodeResp, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

// User login
func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// Get current user info
func (s *UserServer) GetMe(ctx context.Context, in *pb.GetMeReq) (*pb.GetMeResp, error) {
	l := logic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

// User sign in
func (s *UserServer) SignIn(ctx context.Context, in *pb.SignInReq) (*pb.SignInResp, error) {
	l := logic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}

// Get sign in count
func (s *UserServer) GetSignCount(ctx context.Context, in *pb.GetSignCountReq) (*pb.GetSignCountResp, error) {
	l := logic.NewGetSignCountLogic(ctx, s.svcCtx)
	return l.GetSignCount(in)
}

// Follow user
func (s *UserServer) FollowUser(ctx context.Context, in *pb.FollowUserReq) (*pb.FollowUserResp, error) {
	l := logic.NewFollowUserLogic(ctx, s.svcCtx)
	return l.FollowUser(in)
}

// Unfollow user
func (s *UserServer) UnfollowUser(ctx context.Context, in *pb.UnfollowUserReq) (*pb.UnfollowUserResp, error) {
	l := logic.NewUnfollowUserLogic(ctx, s.svcCtx)
	return l.UnfollowUser(in)
}

// Check if following
func (s *UserServer) IsFollowing(ctx context.Context, in *pb.IsFollowingReq) (*pb.IsFollowingResp, error) {
	l := logic.NewIsFollowingLogic(ctx, s.svcCtx)
	return l.IsFollowing(in)
}

// Get common follows
func (s *UserServer) GetCommonFollows(ctx context.Context, in *pb.GetCommonFollowsReq) (*pb.GetCommonFollowsResp, error) {
	l := logic.NewGetCommonFollowsLogic(ctx, s.svcCtx)
	return l.GetCommonFollows(in)
}
