// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbVoucherOrderFieldNames          = builder.RawFieldNames(&TbVoucherOrder{})
	tbVoucherOrderRows                = strings.Join(tbVoucherOrderFieldNames, ",")
	tbVoucherOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(tbVoucherOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbVoucherOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(tbVoucherOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbVoucherOrderIdPrefix = "cache:tbVoucherOrder:id:"
)

type (
	tbVoucherOrderModel interface {
		Insert(ctx context.Context, data *TbVoucherOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TbVoucherOrder, error)
		Update(ctx context.Context, data *TbVoucherOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTbVoucherOrderModel struct {
		sqlc.CachedConn
		table string
	}

	TbVoucherOrder struct {
		Id         int64        `db:"id"`          // 主键
		UserId     uint64       `db:"user_id"`     // 下单的用户id
		VoucherId  uint64       `db:"voucher_id"`  // 购买的代金券id
		PayType    uint64       `db:"pay_type"`    // 支付方式 1：余额支付；2：支付宝；3：微信
		Status     uint64       `db:"status"`      // 订单状态，1：未支付；2：已支付；3：已核销；4：已取消；5：退款中；6：已退款
		CreateTime time.Time    `db:"create_time"` // 下单时间
		PayTime    sql.NullTime `db:"pay_time"`    // 支付时间
		UseTime    sql.NullTime `db:"use_time"`    // 核销时间
		RefundTime sql.NullTime `db:"refund_time"` // 退款时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
	}
)

func newTbVoucherOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbVoucherOrderModel {
	return &defaultTbVoucherOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_voucher_order`",
	}
}

func (m *defaultTbVoucherOrderModel) Delete(ctx context.Context, id int64) error {
	tbVoucherOrderIdKey := fmt.Sprintf("%s%v", cacheTbVoucherOrderIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbVoucherOrderIdKey)
	return err
}

func (m *defaultTbVoucherOrderModel) FindOne(ctx context.Context, id int64) (*TbVoucherOrder, error) {
	tbVoucherOrderIdKey := fmt.Sprintf("%s%v", cacheTbVoucherOrderIdPrefix, id)
	var resp TbVoucherOrder
	err := m.QueryRowCtx(ctx, &resp, tbVoucherOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbVoucherOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbVoucherOrderModel) Insert(ctx context.Context, data *TbVoucherOrder) (sql.Result, error) {
	tbVoucherOrderIdKey := fmt.Sprintf("%s%v", cacheTbVoucherOrderIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tbVoucherOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.VoucherId, data.PayType, data.Status, data.PayTime, data.UseTime, data.RefundTime)
	}, tbVoucherOrderIdKey)
	return ret, err
}

func (m *defaultTbVoucherOrderModel) Update(ctx context.Context, data *TbVoucherOrder) error {
	tbVoucherOrderIdKey := fmt.Sprintf("%s%v", cacheTbVoucherOrderIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbVoucherOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.VoucherId, data.PayType, data.Status, data.PayTime, data.UseTime, data.RefundTime, data.Id)
	}, tbVoucherOrderIdKey)
	return err
}

func (m *defaultTbVoucherOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbVoucherOrderIdPrefix, primary)
}

func (m *defaultTbVoucherOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbVoucherOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbVoucherOrderModel) tableName() string {
	return m.table
}
