// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Blog struct {
	Id         int64  `json:"id"`
	ShopId     int64  `json:"shopId"`
	UserId     int64  `json:"userId"`
	Title      string `json:"title"`
	Images     string `json:"images"`
	Content    string `json:"content"`
	Liked      int    `json:"liked"`
	Comments   int    `json:"comments"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
	Icon       string `json:"icon,omitempty"`
	Name       string `json:"name,omitempty"`
	IsLike     bool   `json:"isLike,omitempty"`
}

type Shop struct {
	Id         int64   `json:"id"`
	Name       string  `json:"name"`
	TypeId     int64   `json:"typeId"`
	Images     string  `json:"images"`
	Area       string  `json:"area"`
	Address    string  `json:"address"`
	X          float64 `json:"x"`
	Y          float64 `json:"y"`
	AvgPrice   int64   `json:"avgPrice"`
	Sold       int     `json:"sold"`
	Comments   int     `json:"comments"`
	Score      int     `json:"score"`
	OpenHours  string  `json:"openHours"`
	CreateTime string  `json:"createTime"`
	UpdateTime string  `json:"updateTime"`
	Distance   float64 `json:"distance,omitempty"`
}

type ShopType struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"`
	Sort int    `json:"sort"`
}

type UserDetailInfo struct {
	Id        int64  `json:"id,omitempty"`
	City      string `json:"city,omitempty"`
	Introduce string `json:"introduce,omitempty"`
	Fans      int    `json:"fans,omitempty"`
	Followee  int    `json:"followee,omitempty"`
	Gender    int    `json:"gender,omitempty"`
	Birthday  string `json:"birthday,omitempty"`
	Credits   int    `json:"credits,omitempty"`
	Level     int    `json:"level,omitempty"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Phone    string `json:"phone"`
	NickName string `json:"nickname"`
	Icon     string `json:"icon"`
}

type Voucher struct {
	Id          int64  `json:"id"`
	ShopId      int64  `json:"shopId"`
	Title       string `json:"title"`
	SubTitle    string `json:"subTitle"`
	Rules       string `json:"rules"`
	PayValue    int64  `json:"payValue"`
	ActualValue int64  `json:"actualValue"`
	Type        int    `json:"type"` // 1=普通券 2=秒杀券
	Status      int    `json:"status"`
	Stock       int    `json:"stock,omitempty"`
	BeginTime   string `json:"beginTime,omitempty"`
	EndTime     string `json:"endTime,omitempty"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type AddSeckillVoucherReq struct {
	ShopId      int64  `json:"shopId"`
	Title       string `json:"title"`
	SubTitle    string `json:"subTitle"`
	Rules       string `json:"rules"`
	PayValue    int64  `json:"payValue"`
	ActualValue int64  `json:"actualValue"`
	Stock       int    `json:"stock"`
	BeginTime   string `json:"beginTime"`
	EndTime     string `json:"endTime"`
}

type AddSeckillVoucherRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int64  `json:"data,omitempty"` // voucher id
}

type AddVoucherReq struct {
	ShopId      int64  `json:"shopId"`
	Title       string `json:"title"`
	SubTitle    string `json:"subTitle"`
	Rules       string `json:"rules"`
	PayValue    int64  `json:"payValue"`
	ActualValue int64  `json:"actualValue"`
}

type AddVoucherRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int64  `json:"data,omitempty"` // voucher id
}

type DeleteBlogImgReq struct {
	Name string `form:"name"`
}

type DeleteBlogImgRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type FollowCommonsReq struct {
	Id int64 `path:"id"`
}

type FollowCommonsRsp struct {
	Success bool        `json:"success"`
	ErrMsg  string      `json:"errMsg,omitempty"`
	Data    interface{} `json:"data,omitempty"` // user list
}

type FollowReq struct {
	Id       int64 `path:"id"`
	IsFollow bool  `path:"isFollow"`
}

type FollowRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type GetMeReq struct {
}

type GetMeRsp struct {
	Success bool      `json:"success"`
	ErrMsg  string    `json:"errMsg,omitempty"`
	Data    *UserInfo `json:"data,omitempty"`
}

type GetUserInfoReq struct {
	UserId int64 `path:"id"`
}

type GetUserInfoRsp struct {
	Success bool            `json:"success"`
	ErrMsg  string          `json:"errMsg,omitempty"`
	Data    *UserDetailInfo `json:"data,omitempty"`
}

type IsFollowReq struct {
	Id int64 `path:"id"`
}

type IsFollowRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    bool   `json:"data,omitempty"`
}

type LikeBlogReq struct {
	Id int64 `path:"id"`
}

type LikeBlogRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type LoginReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    string `json:"data,omitempty"` // token
}

type LogoutReq struct {
}

type LogoutRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type QueryBlogByIdReq struct {
	Id int64 `path:"id"`
}

type QueryBlogByIdRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    *Blog  `json:"data,omitempty"`
}

type QueryBlogByUserIdReq struct {
	Current int64 `form:"current,default=1"`
	Id      int64 `form:"id"`
}

type QueryBlogByUserIdRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    []Blog `json:"data,omitempty"`
}

type QueryBlogLikesReq struct {
	Id int64 `path:"id"`
}

type QueryBlogLikesRsp struct {
	Success bool        `json:"success"`
	ErrMsg  string      `json:"errMsg,omitempty"`
	Data    interface{} `json:"data,omitempty"` // user list
}

type QueryBlogOfFollowReq struct {
	LastId int64 `form:"lastId"`
	Offset int64 `form:"offset,default=0"`
}

type QueryBlogOfFollowRsp struct {
	Success bool        `json:"success"`
	ErrMsg  string      `json:"errMsg,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

type QueryHotBlogReq struct {
	Current int64 `form:"current,default=1"`
}

type QueryHotBlogRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    []Blog `json:"data,omitempty"`
}

type QueryMyBlogReq struct {
	Current int64 `form:"current,default=1"`
}

type QueryMyBlogRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    []Blog `json:"data,omitempty"`
}

type QueryShopByIdReq struct {
	Id int64 `path:"id"`
}

type QueryShopByIdRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    *Shop  `json:"data,omitempty"`
}

type QueryShopByNameReq struct {
	Name    string `form:"name,optional"`
	Current int64  `form:"current,default=1"`
}

type QueryShopByNameRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    []Shop `json:"data,omitempty"`
}

type QueryShopByTypeReq struct {
	TypeId  int64   `form:"typeId"`
	Current int64   `form:"current,default=1"`
	X       float64 `form:"x,optional"`
	Y       float64 `form:"y,optional"`
}

type QueryShopByTypeRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    []Shop `json:"data,omitempty"`
}

type QueryTypeListReq struct {
}

type QueryTypeListRsp struct {
	Success bool       `json:"success"`
	ErrMsg  string     `json:"errMsg,omitempty"`
	Data    []ShopType `json:"data,omitempty"`
}

type QueryUserByIdReq struct {
	UserId int64 `path:"id"`
}

type QueryUserByIdRsp struct {
	Success bool      `json:"success"`
	ErrMsg  string    `json:"errMsg,omitempty"`
	Data    *UserInfo `json:"data,omitempty"`
}

type QueryVoucherOfShopReq struct {
	ShopId int64 `path:"shopId"`
}

type QueryVoucherOfShopRsp struct {
	Success bool      `json:"success"`
	ErrMsg  string    `json:"errMsg,omitempty"`
	Data    []Voucher `json:"data,omitempty"`
}

type SaveBlogReq struct {
	ShopId  int64  `json:"shopId,optional"`
	Title   string `json:"title,optional"`
	Images  string `json:"images,optional"`
	Content string `json:"content,optional"`
}

type SaveBlogRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int64  `json:"data,omitempty"` // blog id
}

type SaveShopReq struct {
	Name      string  `json:"name"`
	TypeId    int64   `json:"typeId"`
	Images    string  `json:"images"`
	Area      string  `json:"area"`
	Address   string  `json:"address"`
	X         float64 `json:"x"`
	Y         float64 `json:"y"`
	AvgPrice  int64   `json:"avgPrice"`
	Sold      int     `json:"sold"`
	Comments  int     `json:"comments"`
	Score     int     `json:"score"`
	OpenHours string  `json:"openHours"`
}

type SaveShopRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int64  `json:"data,omitempty"` // shop id
}

type SeckillVoucherReq struct {
	Id int64 `path:"id"`
}

type SeckillVoucherRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int64  `json:"data,omitempty"` // order id
}

type SendCodeReq struct {
	Phone string `form:"phone"`
}

type SendCodeRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    string `json:"data,omitempty"`
}

type SignCountReq struct {
}

type SignCountRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    int    `json:"data,omitempty"` // 连续签到天数
}

type SignReq struct {
}

type SignRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type UpdateShopReq struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name,omitempty"`
	TypeId    int64   `json:"typeId,omitempty"`
	Images    string  `json:"images,omitempty"`
	Area      string  `json:"area,omitempty"`
	Address   string  `json:"address,omitempty"`
	X         float64 `json:"x,omitempty"`
	Y         float64 `json:"y,omitempty"`
	AvgPrice  int64   `json:"avgPrice,omitempty"`
	Sold      int     `json:"sold,omitempty"`
	Comments  int     `json:"comments,omitempty"`
	Score     int     `json:"score,omitempty"`
	OpenHours string  `json:"openHours,omitempty"`
}

type UpdateShopRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
}

type UploadImageReq struct {
	File string `form:"file"` // multipart file
}

type UploadImageRsp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"errMsg,omitempty"`
	Data    string `json:"data,omitempty"` // file name
}
