// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbBlogCommentsFieldNames          = builder.RawFieldNames(&TbBlogComments{})
	tbBlogCommentsRows                = strings.Join(tbBlogCommentsFieldNames, ",")
	tbBlogCommentsRowsExpectAutoSet   = strings.Join(stringx.Remove(tbBlogCommentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbBlogCommentsRowsWithPlaceHolder = strings.Join(stringx.Remove(tbBlogCommentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbBlogCommentsIdPrefix = "cache:tbBlogComments:id:"
)

type (
	tbBlogCommentsModel interface {
		Insert(ctx context.Context, data *TbBlogComments) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TbBlogComments, error)
		Update(ctx context.Context, data *TbBlogComments) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTbBlogCommentsModel struct {
		sqlc.CachedConn
		table string
	}

	TbBlogComments struct {
		Id         uint64        `db:"id"`          // 主键
		UserId     uint64        `db:"user_id"`     // 用户id
		BlogId     uint64        `db:"blog_id"`     // 探店id
		ParentId   uint64        `db:"parent_id"`   // 关联的1级评论id，如果是一级评论，则值为0
		AnswerId   uint64        `db:"answer_id"`   // 回复的评论id
		Content    string        `db:"content"`     // 回复的内容
		Liked      sql.NullInt64 `db:"liked"`       // 点赞数
		Status     sql.NullInt64 `db:"status"`      // 状态，0：正常，1：被举报，2：禁止查看
		CreateTime time.Time     `db:"create_time"` // 创建时间
		UpdateTime time.Time     `db:"update_time"` // 更新时间
	}
)

func newTbBlogCommentsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbBlogCommentsModel {
	return &defaultTbBlogCommentsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_blog_comments`",
	}
}

func (m *defaultTbBlogCommentsModel) Delete(ctx context.Context, id uint64) error {
	tbBlogCommentsIdKey := fmt.Sprintf("%s%v", cacheTbBlogCommentsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbBlogCommentsIdKey)
	return err
}

func (m *defaultTbBlogCommentsModel) FindOne(ctx context.Context, id uint64) (*TbBlogComments, error) {
	tbBlogCommentsIdKey := fmt.Sprintf("%s%v", cacheTbBlogCommentsIdPrefix, id)
	var resp TbBlogComments
	err := m.QueryRowCtx(ctx, &resp, tbBlogCommentsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbBlogCommentsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbBlogCommentsModel) Insert(ctx context.Context, data *TbBlogComments) (sql.Result, error) {
	tbBlogCommentsIdKey := fmt.Sprintf("%s%v", cacheTbBlogCommentsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tbBlogCommentsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.BlogId, data.ParentId, data.AnswerId, data.Content, data.Liked, data.Status)
	}, tbBlogCommentsIdKey)
	return ret, err
}

func (m *defaultTbBlogCommentsModel) Update(ctx context.Context, data *TbBlogComments) error {
	tbBlogCommentsIdKey := fmt.Sprintf("%s%v", cacheTbBlogCommentsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbBlogCommentsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.BlogId, data.ParentId, data.AnswerId, data.Content, data.Liked, data.Status, data.Id)
	}, tbBlogCommentsIdKey)
	return err
}

func (m *defaultTbBlogCommentsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbBlogCommentsIdPrefix, primary)
}

func (m *defaultTbBlogCommentsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbBlogCommentsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbBlogCommentsModel) tableName() string {
	return m.table
}
