// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbBlogFieldNames          = builder.RawFieldNames(&TbBlog{})
	tbBlogRows                = strings.Join(tbBlogFieldNames, ",")
	tbBlogRowsExpectAutoSet   = strings.Join(stringx.Remove(tbBlogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbBlogRowsWithPlaceHolder = strings.Join(stringx.Remove(tbBlogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbBlogIdPrefix = "cache:tbBlog:id:"
)

type (
	tbBlogModel interface {
		Insert(ctx context.Context, data *TbBlog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TbBlog, error)
		Update(ctx context.Context, data *TbBlog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTbBlogModel struct {
		sqlc.CachedConn
		table string
	}

	TbBlog struct {
		Id         uint64        `db:"id"`          // 主键
		ShopId     int64         `db:"shop_id"`     // 商户id
		UserId     uint64        `db:"user_id"`     // 用户id
		Title      string        `db:"title"`       // 标题
		Images     string        `db:"images"`      // 探店的照片，最多9张，多张以\",\"隔开
		Content    string        `db:"content"`     // 探店的文字描述
		Liked      uint64        `db:"liked"`       // 点赞数量
		Comments   sql.NullInt64 `db:"comments"`    // 评论数量
		CreateTime time.Time     `db:"create_time"` // 创建时间
		UpdateTime time.Time     `db:"update_time"` // 更新时间
	}
)

func newTbBlogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbBlogModel {
	return &defaultTbBlogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_blog`",
	}
}

func (m *defaultTbBlogModel) Delete(ctx context.Context, id uint64) error {
	tbBlogIdKey := fmt.Sprintf("%s%v", cacheTbBlogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbBlogIdKey)
	return err
}

func (m *defaultTbBlogModel) FindOne(ctx context.Context, id uint64) (*TbBlog, error) {
	tbBlogIdKey := fmt.Sprintf("%s%v", cacheTbBlogIdPrefix, id)
	var resp TbBlog
	err := m.QueryRowCtx(ctx, &resp, tbBlogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbBlogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbBlogModel) Insert(ctx context.Context, data *TbBlog) (sql.Result, error) {
	tbBlogIdKey := fmt.Sprintf("%s%v", cacheTbBlogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tbBlogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ShopId, data.UserId, data.Title, data.Images, data.Content, data.Liked, data.Comments)
	}, tbBlogIdKey)
	return ret, err
}

func (m *defaultTbBlogModel) Update(ctx context.Context, data *TbBlog) error {
	tbBlogIdKey := fmt.Sprintf("%s%v", cacheTbBlogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbBlogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ShopId, data.UserId, data.Title, data.Images, data.Content, data.Liked, data.Comments, data.Id)
	}, tbBlogIdKey)
	return err
}

func (m *defaultTbBlogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbBlogIdPrefix, primary)
}

func (m *defaultTbBlogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbBlogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbBlogModel) tableName() string {
	return m.table
}
