// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	blog "github.com/me-cs/dianping-gozero/api/internal/handler/blog"
	follow "github.com/me-cs/dianping-gozero/api/internal/handler/follow"
	shop "github.com/me-cs/dianping-gozero/api/internal/handler/shop"
	shopType "github.com/me-cs/dianping-gozero/api/internal/handler/shopType"
	upload "github.com/me-cs/dianping-gozero/api/internal/handler/upload"
	user "github.com/me-cs/dianping-gozero/api/internal/handler/user"
	voucher "github.com/me-cs/dianping-gozero/api/internal/handler/voucher"
	voucherOrder "github.com/me-cs/dianping-gozero/api/internal/handler/voucherOrder"
	"github.com/me-cs/dianping-gozero/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/blog/hot",
					Handler: blog.QueryHotBlogHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/blog",
					Handler: blog.SaveBlogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/blog/:id",
					Handler: blog.QueryBlogByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/blog/like/:id",
					Handler: blog.LikeBlogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/blog/likes/:id",
					Handler: blog.QueryBlogLikesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/blog/of/follow",
					Handler: blog.QueryBlogOfFollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/blog/of/me",
					Handler: blog.QueryMyBlogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/blog/of/user",
					Handler: blog.QueryBlogByUserIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/follow/:id/:isFollow",
					Handler: follow.FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/follow/common/:id",
					Handler: follow.FollowCommonsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/follow/or/not/:id",
					Handler: follow.IsFollowHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/shop/:id",
					Handler: shop.QueryShopByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/shop/of/name",
					Handler: shop.QueryShopByNameHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/shop/of/type",
					Handler: shop.QueryShopByTypeHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/shop",
					Handler: shop.SaveShopHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/shop",
					Handler: shop.UpdateShopHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/shop-type/list",
					Handler: shopType.QueryTypeListHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload/blog",
					Handler: upload.UploadImageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/upload/blog/delete",
					Handler: upload.DeleteBlogImgHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/code",
					Handler: user.SendCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/login",
					Handler: user.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.QueryUserByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/info/:id",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/me",
					Handler: user.GetMeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/sign",
					Handler: user.SignHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/sign/count",
					Handler: user.SignCountHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/voucher/list/:shopId",
					Handler: voucher.QueryVoucherOfShopHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/voucher",
					Handler: voucher.AddVoucherHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/voucher/seckill",
					Handler: voucher.AddSeckillVoucherHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/voucher-order/seckill/:id",
					Handler: voucherOrder.SeckillVoucherHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
