// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: blog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Blog_CreateBlog_FullMethodName         = "/blog.Blog/CreateBlog"
	Blog_GetBlog_FullMethodName            = "/blog.Blog/GetBlog"
	Blog_LikeBlog_FullMethodName           = "/blog.Blog/LikeBlog"
	Blog_GetBlogLikes_FullMethodName       = "/blog.Blog/GetBlogLikes"
	Blog_QueryHotBlogs_FullMethodName      = "/blog.Blog/QueryHotBlogs"
	Blog_QueryBlogsByUser_FullMethodName   = "/blog.Blog/QueryBlogsByUser"
	Blog_QueryBlogsOfFollow_FullMethodName = "/blog.Blog/QueryBlogsOfFollow"
)

// BlogClient is the client API for Blog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogClient interface {
	// Create blog
	CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogResp, error)
	// Get blog by ID
	GetBlog(ctx context.Context, in *GetBlogReq, opts ...grpc.CallOption) (*GetBlogResp, error)
	// Like blog
	LikeBlog(ctx context.Context, in *LikeBlogReq, opts ...grpc.CallOption) (*LikeBlogResp, error)
	// Get blog likes
	GetBlogLikes(ctx context.Context, in *GetBlogLikesReq, opts ...grpc.CallOption) (*GetBlogLikesResp, error)
	// Query hot blogs
	QueryHotBlogs(ctx context.Context, in *QueryHotBlogsReq, opts ...grpc.CallOption) (*QueryHotBlogsResp, error)
	// Query blogs by user
	QueryBlogsByUser(ctx context.Context, in *QueryBlogsByUserReq, opts ...grpc.CallOption) (*QueryBlogsByUserResp, error)
	// Query blogs of following users
	QueryBlogsOfFollow(ctx context.Context, in *QueryBlogsOfFollowReq, opts ...grpc.CallOption) (*QueryBlogsOfFollowResp, error)
}

type blogClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogClient(cc grpc.ClientConnInterface) BlogClient {
	return &blogClient{cc}
}

func (c *blogClient) CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogResp, error) {
	out := new(CreateBlogResp)
	err := c.cc.Invoke(ctx, Blog_CreateBlog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetBlog(ctx context.Context, in *GetBlogReq, opts ...grpc.CallOption) (*GetBlogResp, error) {
	out := new(GetBlogResp)
	err := c.cc.Invoke(ctx, Blog_GetBlog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) LikeBlog(ctx context.Context, in *LikeBlogReq, opts ...grpc.CallOption) (*LikeBlogResp, error) {
	out := new(LikeBlogResp)
	err := c.cc.Invoke(ctx, Blog_LikeBlog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetBlogLikes(ctx context.Context, in *GetBlogLikesReq, opts ...grpc.CallOption) (*GetBlogLikesResp, error) {
	out := new(GetBlogLikesResp)
	err := c.cc.Invoke(ctx, Blog_GetBlogLikes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) QueryHotBlogs(ctx context.Context, in *QueryHotBlogsReq, opts ...grpc.CallOption) (*QueryHotBlogsResp, error) {
	out := new(QueryHotBlogsResp)
	err := c.cc.Invoke(ctx, Blog_QueryHotBlogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) QueryBlogsByUser(ctx context.Context, in *QueryBlogsByUserReq, opts ...grpc.CallOption) (*QueryBlogsByUserResp, error) {
	out := new(QueryBlogsByUserResp)
	err := c.cc.Invoke(ctx, Blog_QueryBlogsByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) QueryBlogsOfFollow(ctx context.Context, in *QueryBlogsOfFollowReq, opts ...grpc.CallOption) (*QueryBlogsOfFollowResp, error) {
	out := new(QueryBlogsOfFollowResp)
	err := c.cc.Invoke(ctx, Blog_QueryBlogsOfFollow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServer is the server API for Blog service.
// All implementations must embed UnimplementedBlogServer
// for forward compatibility
type BlogServer interface {
	// Create blog
	CreateBlog(context.Context, *CreateBlogReq) (*CreateBlogResp, error)
	// Get blog by ID
	GetBlog(context.Context, *GetBlogReq) (*GetBlogResp, error)
	// Like blog
	LikeBlog(context.Context, *LikeBlogReq) (*LikeBlogResp, error)
	// Get blog likes
	GetBlogLikes(context.Context, *GetBlogLikesReq) (*GetBlogLikesResp, error)
	// Query hot blogs
	QueryHotBlogs(context.Context, *QueryHotBlogsReq) (*QueryHotBlogsResp, error)
	// Query blogs by user
	QueryBlogsByUser(context.Context, *QueryBlogsByUserReq) (*QueryBlogsByUserResp, error)
	// Query blogs of following users
	QueryBlogsOfFollow(context.Context, *QueryBlogsOfFollowReq) (*QueryBlogsOfFollowResp, error)
	mustEmbedUnimplementedBlogServer()
}

// UnimplementedBlogServer must be embedded to have forward compatible implementations.
type UnimplementedBlogServer struct {
}

func (UnimplementedBlogServer) CreateBlog(context.Context, *CreateBlogReq) (*CreateBlogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlog not implemented")
}
func (UnimplementedBlogServer) GetBlog(context.Context, *GetBlogReq) (*GetBlogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlog not implemented")
}
func (UnimplementedBlogServer) LikeBlog(context.Context, *LikeBlogReq) (*LikeBlogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeBlog not implemented")
}
func (UnimplementedBlogServer) GetBlogLikes(context.Context, *GetBlogLikesReq) (*GetBlogLikesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogLikes not implemented")
}
func (UnimplementedBlogServer) QueryHotBlogs(context.Context, *QueryHotBlogsReq) (*QueryHotBlogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryHotBlogs not implemented")
}
func (UnimplementedBlogServer) QueryBlogsByUser(context.Context, *QueryBlogsByUserReq) (*QueryBlogsByUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBlogsByUser not implemented")
}
func (UnimplementedBlogServer) QueryBlogsOfFollow(context.Context, *QueryBlogsOfFollowReq) (*QueryBlogsOfFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBlogsOfFollow not implemented")
}
func (UnimplementedBlogServer) mustEmbedUnimplementedBlogServer() {}

// UnsafeBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServer will
// result in compilation errors.
type UnsafeBlogServer interface {
	mustEmbedUnimplementedBlogServer()
}

func RegisterBlogServer(s grpc.ServiceRegistrar, srv BlogServer) {
	s.RegisterService(&Blog_ServiceDesc, srv)
}

func _Blog_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_CreateBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).CreateBlog(ctx, req.(*CreateBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetBlog(ctx, req.(*GetBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_LikeBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).LikeBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_LikeBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).LikeBlog(ctx, req.(*LikeBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetBlogLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogLikesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetBlogLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetBlogLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetBlogLikes(ctx, req.(*GetBlogLikesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_QueryHotBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHotBlogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).QueryHotBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_QueryHotBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).QueryHotBlogs(ctx, req.(*QueryHotBlogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_QueryBlogsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlogsByUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).QueryBlogsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_QueryBlogsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).QueryBlogsByUser(ctx, req.(*QueryBlogsByUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_QueryBlogsOfFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlogsOfFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).QueryBlogsOfFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_QueryBlogsOfFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).QueryBlogsOfFollow(ctx, req.(*QueryBlogsOfFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Blog_ServiceDesc is the grpc.ServiceDesc for Blog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.Blog",
	HandlerType: (*BlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _Blog_CreateBlog_Handler,
		},
		{
			MethodName: "GetBlog",
			Handler:    _Blog_GetBlog_Handler,
		},
		{
			MethodName: "LikeBlog",
			Handler:    _Blog_LikeBlog_Handler,
		},
		{
			MethodName: "GetBlogLikes",
			Handler:    _Blog_GetBlogLikes_Handler,
		},
		{
			MethodName: "QueryHotBlogs",
			Handler:    _Blog_QueryHotBlogs_Handler,
		},
		{
			MethodName: "QueryBlogsByUser",
			Handler:    _Blog_QueryBlogsByUser_Handler,
		},
		{
			MethodName: "QueryBlogsOfFollow",
			Handler:    _Blog_QueryBlogsOfFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}
