// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: shop.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Shop_GetShop_FullMethodName         = "/shop.Shop/GetShop"
	Shop_ListShopsByType_FullMethodName = "/shop.Shop/ListShopsByType"
	Shop_SearchShops_FullMethodName     = "/shop.Shop/SearchShops"
	Shop_GetShopType_FullMethodName     = "/shop.Shop/GetShopType"
	Shop_ListShopTypes_FullMethodName   = "/shop.Shop/ListShopTypes"
)

// ShopClient is the client API for Shop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopClient interface {
	// Get shop by ID
	GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*GetShopResp, error)
	// List shops by type
	ListShopsByType(ctx context.Context, in *ListShopsByTypeReq, opts ...grpc.CallOption) (*ListShopsByTypeResp, error)
	// Search shops
	SearchShops(ctx context.Context, in *SearchShopsReq, opts ...grpc.CallOption) (*SearchShopsResp, error)
	// Get shop type by ID
	GetShopType(ctx context.Context, in *GetShopTypeReq, opts ...grpc.CallOption) (*GetShopTypeResp, error)
	// List all shop types
	ListShopTypes(ctx context.Context, in *ListShopTypesReq, opts ...grpc.CallOption) (*ListShopTypesResp, error)
}

type shopClient struct {
	cc grpc.ClientConnInterface
}

func NewShopClient(cc grpc.ClientConnInterface) ShopClient {
	return &shopClient{cc}
}

func (c *shopClient) GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*GetShopResp, error) {
	out := new(GetShopResp)
	err := c.cc.Invoke(ctx, Shop_GetShop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) ListShopsByType(ctx context.Context, in *ListShopsByTypeReq, opts ...grpc.CallOption) (*ListShopsByTypeResp, error) {
	out := new(ListShopsByTypeResp)
	err := c.cc.Invoke(ctx, Shop_ListShopsByType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) SearchShops(ctx context.Context, in *SearchShopsReq, opts ...grpc.CallOption) (*SearchShopsResp, error) {
	out := new(SearchShopsResp)
	err := c.cc.Invoke(ctx, Shop_SearchShops_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) GetShopType(ctx context.Context, in *GetShopTypeReq, opts ...grpc.CallOption) (*GetShopTypeResp, error) {
	out := new(GetShopTypeResp)
	err := c.cc.Invoke(ctx, Shop_GetShopType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) ListShopTypes(ctx context.Context, in *ListShopTypesReq, opts ...grpc.CallOption) (*ListShopTypesResp, error) {
	out := new(ListShopTypesResp)
	err := c.cc.Invoke(ctx, Shop_ListShopTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServer is the server API for Shop service.
// All implementations must embed UnimplementedShopServer
// for forward compatibility
type ShopServer interface {
	// Get shop by ID
	GetShop(context.Context, *GetShopReq) (*GetShopResp, error)
	// List shops by type
	ListShopsByType(context.Context, *ListShopsByTypeReq) (*ListShopsByTypeResp, error)
	// Search shops
	SearchShops(context.Context, *SearchShopsReq) (*SearchShopsResp, error)
	// Get shop type by ID
	GetShopType(context.Context, *GetShopTypeReq) (*GetShopTypeResp, error)
	// List all shop types
	ListShopTypes(context.Context, *ListShopTypesReq) (*ListShopTypesResp, error)
	mustEmbedUnimplementedShopServer()
}

// UnimplementedShopServer must be embedded to have forward compatible implementations.
type UnimplementedShopServer struct {
}

func (UnimplementedShopServer) GetShop(context.Context, *GetShopReq) (*GetShopResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedShopServer) ListShopsByType(context.Context, *ListShopsByTypeReq) (*ListShopsByTypeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShopsByType not implemented")
}
func (UnimplementedShopServer) SearchShops(context.Context, *SearchShopsReq) (*SearchShopsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShops not implemented")
}
func (UnimplementedShopServer) GetShopType(context.Context, *GetShopTypeReq) (*GetShopTypeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopType not implemented")
}
func (UnimplementedShopServer) ListShopTypes(context.Context, *ListShopTypesReq) (*ListShopTypesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShopTypes not implemented")
}
func (UnimplementedShopServer) mustEmbedUnimplementedShopServer() {}

// UnsafeShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServer will
// result in compilation errors.
type UnsafeShopServer interface {
	mustEmbedUnimplementedShopServer()
}

func RegisterShopServer(s grpc.ServiceRegistrar, srv ShopServer) {
	s.RegisterService(&Shop_ServiceDesc, srv)
}

func _Shop_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).GetShop(ctx, req.(*GetShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_ListShopsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopsByTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).ListShopsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_ListShopsByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).ListShopsByType(ctx, req.(*ListShopsByTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_SearchShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShopsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).SearchShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_SearchShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).SearchShops(ctx, req.(*SearchShopsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_GetShopType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).GetShopType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_GetShopType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).GetShopType(ctx, req.(*GetShopTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_ListShopTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopTypesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).ListShopTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shop_ListShopTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).ListShopTypes(ctx, req.(*ListShopTypesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Shop_ServiceDesc is the grpc.ServiceDesc for Shop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.Shop",
	HandlerType: (*ShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShop",
			Handler:    _Shop_GetShop_Handler,
		},
		{
			MethodName: "ListShopsByType",
			Handler:    _Shop_ListShopsByType_Handler,
		},
		{
			MethodName: "SearchShops",
			Handler:    _Shop_SearchShops_Handler,
		},
		{
			MethodName: "GetShopType",
			Handler:    _Shop_GetShopType_Handler,
		},
		{
			MethodName: "ListShopTypes",
			Handler:    _Shop_ListShopTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
