// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbSeckillVoucherFieldNames          = builder.RawFieldNames(&TbSeckillVoucher{})
	tbSeckillVoucherRows                = strings.Join(tbSeckillVoucherFieldNames, ",")
	tbSeckillVoucherRowsExpectAutoSet   = strings.Join(stringx.Remove(tbSeckillVoucherFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbSeckillVoucherRowsWithPlaceHolder = strings.Join(stringx.Remove(tbSeckillVoucherFieldNames, "`voucher_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbSeckillVoucherVoucherIdPrefix = "cache:tbSeckillVoucher:voucherId:"
)

type (
	tbSeckillVoucherModel interface {
		Insert(ctx context.Context, data *TbSeckillVoucher) (sql.Result, error)
		FindOne(ctx context.Context, voucherId uint64) (*TbSeckillVoucher, error)
		Update(ctx context.Context, data *TbSeckillVoucher) error
		Delete(ctx context.Context, voucherId uint64) error
	}

	defaultTbSeckillVoucherModel struct {
		sqlc.CachedConn
		table string
	}

	TbSeckillVoucher struct {
		VoucherId  uint64    `db:"voucher_id"`  // 关联的优惠券的id
		Stock      int64     `db:"stock"`       // 库存
		CreateTime time.Time `db:"create_time"` // 创建时间
		BeginTime  time.Time `db:"begin_time"`  // 生效时间
		EndTime    time.Time `db:"end_time"`    // 失效时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newTbSeckillVoucherModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbSeckillVoucherModel {
	return &defaultTbSeckillVoucherModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_seckill_voucher`",
	}
}

func (m *defaultTbSeckillVoucherModel) Delete(ctx context.Context, voucherId uint64) error {
	tbSeckillVoucherVoucherIdKey := fmt.Sprintf("%s%v", cacheTbSeckillVoucherVoucherIdPrefix, voucherId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `voucher_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, voucherId)
	}, tbSeckillVoucherVoucherIdKey)
	return err
}

func (m *defaultTbSeckillVoucherModel) FindOne(ctx context.Context, voucherId uint64) (*TbSeckillVoucher, error) {
	tbSeckillVoucherVoucherIdKey := fmt.Sprintf("%s%v", cacheTbSeckillVoucherVoucherIdPrefix, voucherId)
	var resp TbSeckillVoucher
	err := m.QueryRowCtx(ctx, &resp, tbSeckillVoucherVoucherIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `voucher_id` = ? limit 1", tbSeckillVoucherRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, voucherId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbSeckillVoucherModel) Insert(ctx context.Context, data *TbSeckillVoucher) (sql.Result, error) {
	tbSeckillVoucherVoucherIdKey := fmt.Sprintf("%s%v", cacheTbSeckillVoucherVoucherIdPrefix, data.VoucherId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tbSeckillVoucherRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.VoucherId, data.Stock, data.BeginTime, data.EndTime)
	}, tbSeckillVoucherVoucherIdKey)
	return ret, err
}

func (m *defaultTbSeckillVoucherModel) Update(ctx context.Context, data *TbSeckillVoucher) error {
	tbSeckillVoucherVoucherIdKey := fmt.Sprintf("%s%v", cacheTbSeckillVoucherVoucherIdPrefix, data.VoucherId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `voucher_id` = ?", m.table, tbSeckillVoucherRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Stock, data.BeginTime, data.EndTime, data.VoucherId)
	}, tbSeckillVoucherVoucherIdKey)
	return err
}

func (m *defaultTbSeckillVoucherModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbSeckillVoucherVoucherIdPrefix, primary)
}

func (m *defaultTbSeckillVoucherModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `voucher_id` = ? limit 1", tbSeckillVoucherRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbSeckillVoucherModel) tableName() string {
	return m.table
}
