// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbVoucherFieldNames          = builder.RawFieldNames(&TbVoucher{})
	tbVoucherRows                = strings.Join(tbVoucherFieldNames, ",")
	tbVoucherRowsExpectAutoSet   = strings.Join(stringx.Remove(tbVoucherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbVoucherRowsWithPlaceHolder = strings.Join(stringx.Remove(tbVoucherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbVoucherIdPrefix = "cache:tbVoucher:id:"
)

type (
	tbVoucherModel interface {
		Insert(ctx context.Context, data *TbVoucher) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TbVoucher, error)
		Update(ctx context.Context, data *TbVoucher) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTbVoucherModel struct {
		sqlc.CachedConn
		table string
	}

	TbVoucher struct {
		Id          uint64         `db:"id"`           // 主键
		ShopId      sql.NullInt64  `db:"shop_id"`      // 商铺id
		Title       string         `db:"title"`        // 代金券标题
		SubTitle    sql.NullString `db:"sub_title"`    // 副标题
		Rules       sql.NullString `db:"rules"`        // 使用规则
		PayValue    uint64         `db:"pay_value"`    // 支付金额，单位是分。例如200代表2元
		ActualValue int64          `db:"actual_value"` // 抵扣金额，单位是分。例如200代表2元
		Type        uint64         `db:"type"`         // 0,普通券；1,秒杀券
		Status      uint64         `db:"status"`       // 1,上架; 2,下架; 3,过期
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
		UpdateTime  time.Time      `db:"update_time"`  // 更新时间
	}
)

func newTbVoucherModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbVoucherModel {
	return &defaultTbVoucherModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_voucher`",
	}
}

func (m *defaultTbVoucherModel) Delete(ctx context.Context, id uint64) error {
	tbVoucherIdKey := fmt.Sprintf("%s%v", cacheTbVoucherIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbVoucherIdKey)
	return err
}

func (m *defaultTbVoucherModel) FindOne(ctx context.Context, id uint64) (*TbVoucher, error) {
	tbVoucherIdKey := fmt.Sprintf("%s%v", cacheTbVoucherIdPrefix, id)
	var resp TbVoucher
	err := m.QueryRowCtx(ctx, &resp, tbVoucherIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbVoucherRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbVoucherModel) Insert(ctx context.Context, data *TbVoucher) (sql.Result, error) {
	tbVoucherIdKey := fmt.Sprintf("%s%v", cacheTbVoucherIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tbVoucherRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ShopId, data.Title, data.SubTitle, data.Rules, data.PayValue, data.ActualValue, data.Type, data.Status)
	}, tbVoucherIdKey)
	return ret, err
}

func (m *defaultTbVoucherModel) Update(ctx context.Context, data *TbVoucher) error {
	tbVoucherIdKey := fmt.Sprintf("%s%v", cacheTbVoucherIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbVoucherRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ShopId, data.Title, data.SubTitle, data.Rules, data.PayValue, data.ActualValue, data.Type, data.Status, data.Id)
	}, tbVoucherIdKey)
	return err
}

func (m *defaultTbVoucherModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbVoucherIdPrefix, primary)
}

func (m *defaultTbVoucherModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbVoucherRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbVoucherModel) tableName() string {
	return m.table
}
