// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"github.com/me-cs/dianping-gozero/rpc/order/internal/logic"
	"github.com/me-cs/dianping-gozero/rpc/order/internal/svc"
	"github.com/me-cs/dianping-gozero/rpc/order/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// Create voucher order (seckill)
func (s *OrderServer) CreateVoucherOrder(ctx context.Context, in *pb.CreateVoucherOrderReq) (*pb.CreateVoucherOrderResp, error) {
	l := logic.NewCreateVoucherOrderLogic(ctx, s.svcCtx)
	return l.CreateVoucherOrder(in)
}

// Get voucher order by ID
func (s *OrderServer) GetVoucherOrder(ctx context.Context, in *pb.GetVoucherOrderReq) (*pb.GetVoucherOrderResp, error) {
	l := logic.NewGetVoucherOrderLogic(ctx, s.svcCtx)
	return l.GetVoucherOrder(in)
}

// List voucher orders by user
func (s *OrderServer) ListVoucherOrdersByUser(ctx context.Context, in *pb.ListVoucherOrdersByUserReq) (*pb.ListVoucherOrdersByUserResp, error) {
	l := logic.NewListVoucherOrdersByUserLogic(ctx, s.svcCtx)
	return l.ListVoucherOrdersByUser(in)
}

// Cancel voucher order
func (s *OrderServer) CancelVoucherOrder(ctx context.Context, in *pb.CancelVoucherOrderReq) (*pb.CancelVoucherOrderResp, error) {
	l := logic.NewCancelVoucherOrderLogic(ctx, s.svcCtx)
	return l.CancelVoucherOrder(in)
}

// Pay voucher order
func (s *OrderServer) PayVoucherOrder(ctx context.Context, in *pb.PayVoucherOrderReq) (*pb.PayVoucherOrderResp, error) {
	l := logic.NewPayVoucherOrderLogic(ctx, s.svcCtx)
	return l.PayVoucherOrder(in)
}

// Use voucher order
func (s *OrderServer) UseVoucherOrder(ctx context.Context, in *pb.UseVoucherOrderReq) (*pb.UseVoucherOrderResp, error) {
	l := logic.NewUseVoucherOrderLogic(ctx, s.svcCtx)
	return l.UseVoucherOrder(in)
}
