// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbFollowFieldNames          = builder.RawFieldNames(&TbFollow{})
	tbFollowRows                = strings.Join(tbFollowFieldNames, ",")
	tbFollowRowsExpectAutoSet   = strings.Join(stringx.Remove(tbFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbFollowRowsWithPlaceHolder = strings.Join(stringx.Remove(tbFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbFollowIdPrefix = "cache:tbFollow:id:"
)

type (
	tbFollowModel interface {
		Insert(ctx context.Context, data *TbFollow) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TbFollow, error)
		Update(ctx context.Context, data *TbFollow) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTbFollowModel struct {
		sqlc.CachedConn
		table string
	}

	TbFollow struct {
		Id           int64     `db:"id"`             // 主键
		UserId       uint64    `db:"user_id"`        // 用户id
		FollowUserId uint64    `db:"follow_user_id"` // 关联的用户id
		CreateTime   time.Time `db:"create_time"`    // 创建时间
	}
)

func newTbFollowModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbFollowModel {
	return &defaultTbFollowModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_follow`",
	}
}

func (m *defaultTbFollowModel) Delete(ctx context.Context, id int64) error {
	tbFollowIdKey := fmt.Sprintf("%s%v", cacheTbFollowIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbFollowIdKey)
	return err
}

func (m *defaultTbFollowModel) FindOne(ctx context.Context, id int64) (*TbFollow, error) {
	tbFollowIdKey := fmt.Sprintf("%s%v", cacheTbFollowIdPrefix, id)
	var resp TbFollow
	err := m.QueryRowCtx(ctx, &resp, tbFollowIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbFollowRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbFollowModel) Insert(ctx context.Context, data *TbFollow) (sql.Result, error) {
	tbFollowIdKey := fmt.Sprintf("%s%v", cacheTbFollowIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, tbFollowRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowUserId)
	}, tbFollowIdKey)
	return ret, err
}

func (m *defaultTbFollowModel) Update(ctx context.Context, data *TbFollow) error {
	tbFollowIdKey := fmt.Sprintf("%s%v", cacheTbFollowIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbFollowRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowUserId, data.Id)
	}, tbFollowIdKey)
	return err
}

func (m *defaultTbFollowModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbFollowIdPrefix, primary)
}

func (m *defaultTbFollowModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbFollowRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbFollowModel) tableName() string {
	return m.table
}
