// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbSignFieldNames          = builder.RawFieldNames(&TbSign{})
	tbSignRows                = strings.Join(tbSignFieldNames, ",")
	tbSignRowsExpectAutoSet   = strings.Join(stringx.Remove(tbSignFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbSignRowsWithPlaceHolder = strings.Join(stringx.Remove(tbSignFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbSignIdPrefix = "cache:tbSign:id:"
)

type (
	tbSignModel interface {
		Insert(ctx context.Context, data *TbSign) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TbSign, error)
		Update(ctx context.Context, data *TbSign) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTbSignModel struct {
		sqlc.CachedConn
		table string
	}

	TbSign struct {
		Id       uint64        `db:"id"`        // 主键
		UserId   uint64        `db:"user_id"`   // 用户id
		Year     int64         `db:"year"`      // 签到的年
		Month    int64         `db:"month"`     // 签到的月
		Date     time.Time     `db:"date"`      // 签到的日期
		IsBackup sql.NullInt64 `db:"is_backup"` // 是否补签
	}
)

func newTbSignModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbSignModel {
	return &defaultTbSignModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_sign`",
	}
}

func (m *defaultTbSignModel) Delete(ctx context.Context, id uint64) error {
	tbSignIdKey := fmt.Sprintf("%s%v", cacheTbSignIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tbSignIdKey)
	return err
}

func (m *defaultTbSignModel) FindOne(ctx context.Context, id uint64) (*TbSign, error) {
	tbSignIdKey := fmt.Sprintf("%s%v", cacheTbSignIdPrefix, id)
	var resp TbSign
	err := m.QueryRowCtx(ctx, &resp, tbSignIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbSignRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbSignModel) Insert(ctx context.Context, data *TbSign) (sql.Result, error) {
	tbSignIdKey := fmt.Sprintf("%s%v", cacheTbSignIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tbSignRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Year, data.Month, data.Date, data.IsBackup)
	}, tbSignIdKey)
	return ret, err
}

func (m *defaultTbSignModel) Update(ctx context.Context, data *TbSign) error {
	tbSignIdKey := fmt.Sprintf("%s%v", cacheTbSignIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbSignRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Year, data.Month, data.Date, data.IsBackup, data.Id)
	}, tbSignIdKey)
	return err
}

func (m *defaultTbSignModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbSignIdPrefix, primary)
}

func (m *defaultTbSignModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbSignRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbSignModel) tableName() string {
	return m.table
}
