// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbUserInfoFieldNames          = builder.RawFieldNames(&TbUserInfo{})
	tbUserInfoRows                = strings.Join(tbUserInfoFieldNames, ",")
	tbUserInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(tbUserInfoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbUserInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(tbUserInfoFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTbUserInfoUserIdPrefix = "cache:tbUserInfo:userId:"
)

type (
	tbUserInfoModel interface {
		Insert(ctx context.Context, data *TbUserInfo) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*TbUserInfo, error)
		Update(ctx context.Context, data *TbUserInfo) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultTbUserInfoModel struct {
		sqlc.CachedConn
		table string
	}

	TbUserInfo struct {
		UserId     uint64         `db:"user_id"`     // 主键，用户id
		City       string         `db:"city"`        // 城市名称
		Introduce  sql.NullString `db:"introduce"`   // 个人介绍，不要超过128个字符
		Fans       uint64         `db:"fans"`        // 粉丝数量
		Followee   uint64         `db:"followee"`    // 关注的人的数量
		Gender     uint64         `db:"gender"`      // 性别，0：男，1：女
		Birthday   sql.NullTime   `db:"birthday"`    // 生日
		Credits    uint64         `db:"credits"`     // 积分
		Level      uint64         `db:"level"`       // 会员级别，0~9级,0代表未开通会员
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
	}
)

func newTbUserInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTbUserInfoModel {
	return &defaultTbUserInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tb_user_info`",
	}
}

func (m *defaultTbUserInfoModel) Delete(ctx context.Context, userId uint64) error {
	tbUserInfoUserIdKey := fmt.Sprintf("%s%v", cacheTbUserInfoUserIdPrefix, userId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, userId)
	}, tbUserInfoUserIdKey)
	return err
}

func (m *defaultTbUserInfoModel) FindOne(ctx context.Context, userId uint64) (*TbUserInfo, error) {
	tbUserInfoUserIdKey := fmt.Sprintf("%s%v", cacheTbUserInfoUserIdPrefix, userId)
	var resp TbUserInfo
	err := m.QueryRowCtx(ctx, &resp, tbUserInfoUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", tbUserInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbUserInfoModel) Insert(ctx context.Context, data *TbUserInfo) (sql.Result, error) {
	tbUserInfoUserIdKey := fmt.Sprintf("%s%v", cacheTbUserInfoUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tbUserInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.City, data.Introduce, data.Fans, data.Followee, data.Gender, data.Birthday, data.Credits, data.Level)
	}, tbUserInfoUserIdKey)
	return ret, err
}

func (m *defaultTbUserInfoModel) Update(ctx context.Context, data *TbUserInfo) error {
	tbUserInfoUserIdKey := fmt.Sprintf("%s%v", cacheTbUserInfoUserIdPrefix, data.UserId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, tbUserInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.City, data.Introduce, data.Fans, data.Followee, data.Gender, data.Birthday, data.Credits, data.Level, data.UserId)
	}, tbUserInfoUserIdKey)
	return err
}

func (m *defaultTbUserInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTbUserInfoUserIdPrefix, primary)
}

func (m *defaultTbUserInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", tbUserInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbUserInfoModel) tableName() string {
	return m.table
}
