// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voucher.proto

package server

import (
	"context"

	"github.com/me-cs/dianping-gozero/rpc/voucher/internal/logic"
	"github.com/me-cs/dianping-gozero/rpc/voucher/internal/svc"
	"github.com/me-cs/dianping-gozero/rpc/voucher/pb"
)

type VoucherServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVoucherServer
}

func NewVoucherServer(svcCtx *svc.ServiceContext) *VoucherServer {
	return &VoucherServer{
		svcCtx: svcCtx,
	}
}

// Add voucher
func (s *VoucherServer) AddVoucher(ctx context.Context, in *pb.AddVoucherReq) (*pb.AddVoucherResp, error) {
	l := logic.NewAddVoucherLogic(ctx, s.svcCtx)
	return l.AddVoucher(in)
}

// Add seckill voucher
func (s *VoucherServer) AddSeckillVoucher(ctx context.Context, in *pb.AddSeckillVoucherReq) (*pb.AddSeckillVoucherResp, error) {
	l := logic.NewAddSeckillVoucherLogic(ctx, s.svcCtx)
	return l.AddSeckillVoucher(in)
}

// Get voucher by ID
func (s *VoucherServer) GetVoucher(ctx context.Context, in *pb.GetVoucherReq) (*pb.GetVoucherResp, error) {
	l := logic.NewGetVoucherLogic(ctx, s.svcCtx)
	return l.GetVoucher(in)
}

// List vouchers by shop
func (s *VoucherServer) ListVouchersByShop(ctx context.Context, in *pb.ListVouchersByShopReq) (*pb.ListVouchersByShopResp, error) {
	l := logic.NewListVouchersByShopLogic(ctx, s.svcCtx)
	return l.ListVouchersByShop(in)
}

// Check voucher stock
func (s *VoucherServer) CheckVoucherStock(ctx context.Context, in *pb.CheckVoucherStockReq) (*pb.CheckVoucherStockResp, error) {
	l := logic.NewCheckVoucherStockLogic(ctx, s.svcCtx)
	return l.CheckVoucherStock(in)
}

// Deduct voucher stock
func (s *VoucherServer) DeductVoucherStock(ctx context.Context, in *pb.DeductVoucherStockReq) (*pb.DeductVoucherStockResp, error) {
	l := logic.NewDeductVoucherStockLogic(ctx, s.svcCtx)
	return l.DeductVoucherStock(in)
}
