// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package server

import (
	"context"

	"github.com/me-cs/dianping-gozero/rpc/blog/internal/logic"
	"github.com/me-cs/dianping-gozero/rpc/blog/internal/svc"
	"github.com/me-cs/dianping-gozero/rpc/blog/pb"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

// Create blog
func (s *BlogServer) CreateBlog(ctx context.Context, in *pb.CreateBlogReq) (*pb.CreateBlogResp, error) {
	l := logic.NewCreateBlogLogic(ctx, s.svcCtx)
	return l.CreateBlog(in)
}

// Get blog by ID
func (s *BlogServer) GetBlog(ctx context.Context, in *pb.GetBlogReq) (*pb.GetBlogResp, error) {
	l := logic.NewGetBlogLogic(ctx, s.svcCtx)
	return l.GetBlog(in)
}

// Like blog
func (s *BlogServer) LikeBlog(ctx context.Context, in *pb.LikeBlogReq) (*pb.LikeBlogResp, error) {
	l := logic.NewLikeBlogLogic(ctx, s.svcCtx)
	return l.LikeBlog(in)
}

// Get blog likes
func (s *BlogServer) GetBlogLikes(ctx context.Context, in *pb.GetBlogLikesReq) (*pb.GetBlogLikesResp, error) {
	l := logic.NewGetBlogLikesLogic(ctx, s.svcCtx)
	return l.GetBlogLikes(in)
}

// Query hot blogs
func (s *BlogServer) QueryHotBlogs(ctx context.Context, in *pb.QueryHotBlogsReq) (*pb.QueryHotBlogsResp, error) {
	l := logic.NewQueryHotBlogsLogic(ctx, s.svcCtx)
	return l.QueryHotBlogs(in)
}

// Query blogs by user
func (s *BlogServer) QueryBlogsByUser(ctx context.Context, in *pb.QueryBlogsByUserReq) (*pb.QueryBlogsByUserResp, error) {
	l := logic.NewQueryBlogsByUserLogic(ctx, s.svcCtx)
	return l.QueryBlogsByUser(in)
}

// Query blogs of following users
func (s *BlogServer) QueryBlogsOfFollow(ctx context.Context, in *pb.QueryBlogsOfFollowReq) (*pb.QueryBlogsOfFollowResp, error) {
	l := logic.NewQueryBlogsOfFollowLogic(ctx, s.svcCtx)
	return l.QueryBlogsOfFollow(in)
}
